### ISSUE TITLE
Datastore as stand-alone service

### ISSUE THREAD

**Issue by themihai** [AppScale/appscale#2392]
I need to migrate several apps from Appengine to a different platform(cloudfoundry). The issue is that most of them rely on datastore and the cost of migrating to an entirely different database would be too high. 
 Therefore I'm wondering: Is it possible to run datastore as a stand alone/external service with the appengine-like API/interface? More like the "cloud" [REST / RPC ](https://cloud.google.com/datastore/docs/reference/rpc/)APIs that popped up lately.
 . That way I could deploy (with minimal changes) the apps on cloudfoundry or any other platform and maintain datastore compatibility.

**Comment by cdonati** [comment]
The datastore can be run as a standalone service. Unfortunately, we don't yet have the the full REST API implemented for it. We do plan on implementing it, but for now, it just handles v3 protocol buffer requests that the runtimes generate.

Are the apps you are migrating currently running on Google App Engine? If so, do you need to move the data off of Google Cloud Platform, or just the app? If not, you can use Google's client libraries to make datastore requests directly from your Cloud Foundry app.

**Comment by themihai** [comment]
I need to move the data off Google Datastore too so remote access to GCP using Google's client libraries is not an option. Is there any guide how to set-up, run and access datastore as a stand alone service(i.e. how to set ACLs )?

**Comment by cdonati** [comment]
There wasn't an existing guide, so I just opened a pull request to add the following README to the repo: https://github.com/cdonati/appscale/blob/586c9a234f337f1fd7747239c10dd4b5a6933675/AppDB/README.rst

Unfortunately, there are no ACLs set up. AppScale uses iptables to only allow connections from trusted machines.

Which language is the app written in? That can determine the easiest way to access the service as a client.

**Comment by themihai** [comment]
> Unfortunately, there are no ACLs set up. AppScale uses iptables to only allow connections from trusted machines.

  Ok, this is an easy fix.

> Which language is the app written in? That can determine the easiest way to access the service as a client.

The apps are written in Go. 

> Start the datastore server with appscale-datastore -p x where "x" is the port you would like to start the server on. You probably want to start more than one since each can currenly only handle one request at a time. 

Is there any reason for this limitation? Most databases support some kind  concurrency. Am I supposed to develop a kind of load balancer on route  the requests on various ports?

**Comment by cdonati** [comment]
> The apps are written in Go.

This might be a tricky. The way it works in AppScale, the Go app runtime is started with a configuration that points to an API proxy written in Python. This proxy translates (usually just "unwraps" the request from the RemoteAPI message) the calls from the Go runtime into requests that the datastore will understand. If you use the libraries from the Go SDK as-is, you may need to set up this proxy.

Another option would be to create the protobuf requests manually and send them directly to the datastore. In Python, for example, this can be done using the google.appengine.datastore.datastore_pb module. I'm sure a similar thing is possible with Go, but I haven't tried it.

> Is there any reason for this limitation?

It's something we are actively working on fixing. The datastore is a tornado app, but it doesn't make full use of its asynchronous features. It hasn't been a huge priority up to this point since we start so many of them. The cassandra-driver can actually use quite a bit of CPU, and Python's GIL prevents the process from using more than one CPU at a time. So even if it were fully asynchronous, you'd probably want more than one server unless the usage is light.

> develop a kind of load balancer

AppScale just puts them all behind an HAProxy server with a maxconn of 1 each. This works well for us even in high throughput environments (> 5000 datastore calls/sec).
