### ISSUE TITLE
Access is denied when bootstrap.sh tried to fetch http://s3.amazonaws.com/appscale-build

### ISSUE THREAD

**Issue by xuwenbin** [AppScale/appscale#2393]
**From the screen output**
===========
Fetching go_appengine_sdk_linux_amd64-1.9.48.zip from http://s3.amazonaws.com/appscale-build
failed!

**From the direct access in browser**
======================
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>2D0A4D45D84A2B74</RequestId>
<HostId>
WH0Z7k3ENYxVt79Wcj4juEMKJ9wL6tB6se2bWFmXCt1yvwkR/ivS1O22ixckM/RcAvN2gCxCaOo=
</HostId>
</Error>

**Possible causes**
==========
By googling the issue, it seems due to recently Amazon changed its default security; if you upload a file to a bucket it does not inherit the buckets top level security. You need to put a Bucket Policy in place. In this example I will set the anonymous users to be able to read objects in the bucket.

The entire article explaining the issue can be found at http://www.jppinto.com/2011/12/access-denied-to-file-amazon-s3-bucket/

**Resolution**
=======
Require actions from AppScale team to put a Bucket Policy in place, so that anonymous users to be able to read objects in the bucket.

Regards,

**Comment by cdonati** [comment]
Loading the bucket link gives an "Access Denied" message because not everyone has permission to list all of the objects in the bucket. However, everyone does have permission to read the objects required for the build. What happens when you request, for example, http://s3.amazonaws.com/appscale-build/go_appengine_sdk_linux_amd64-1.9.48.zip from a browser? This works for me even as an anonymous user.

If this still doesn't work for you, please let me know what object store (eg. Google Cloud Storage or Azure Blob Storage) works best for you, and I can replicate the files there.

**Comment by xuwenbin** [comment]
I tried again and believe that it is due to high latency and packet loss rate between my node(s) in China and S3 node(s) in Amazon US rather than permission configuration.


It would be highly appreciated if you could replicate those files in Azure Blob Storage. Google services are entirely banged in China. [☹]


Moreover, once you enable Azure Blob Storage, which script file must I change to utilize the new file location?


-wenbin



________________________________
发件人: Chris Donati <notifications@github.com>
发送时间: 2017年3月27日 10:05
收件人: AppScale/appscale
抄送: xuwenbin; Author
主题: Re: [AppScale/appscale] Access is denied when bootstrap.sh tried to fetch http://s3.amazonaws.com/appscale-build (#2393)


Loading the bucket link gives an "Access Denied" message because not everyone has permission to list all of the objects in the bucket. However, everyone does have permission to read the objects required for the build. What happens when you request, for example, http://s3.amazonaws.com/appscale-build/go_appengine_sdk_linux_amd64-1.9.48.zip from a browser? This works for me even as an anonymous user.

If this still doesn't work for you, please let me know what object store (eg. Google Cloud Storage or Azure Blob Storage) works best for you, and I can replicate the files there.

**Comment by xuwenbin** [comment]
Hi cdonati, did you make changes to the download repo settings in script?

I reran the installation script this morning (China time), and it passed with successful result. However, I didn't find "s3.amazon...." text in output log any more.

-wenbin

**Comment by obino** [comment]
Hello xuwenbin,

we cannot change the whole repo that quickly: we will have to test it,
run few regression testing, and make sure it works for all our
customers. So did your build successfully completed right now?

cheers
graziano

**Comment by xuwenbin** [comment]
@obino the weird thing is, in the new log output, there's no text about "s3.amazon...." any more. I am not even sure whether the so-called "build success" is a real success because I cannot tell why "s3.amazon..." is no long there when it is supposed to be there.

**Comment by xuwenbin** [comment]
Trying to install another instance of appscale, and continue encountering failure when script fetchs appengine-java-sdk-1.8.4.zip from http://s3.amazonaws.com/appscale-build.

I'm wondering whether there is download quatation limit for the S3 bucket of appscale?

-wenbin

**Comment by xuwenbin** [comment]
The entire installation exp. is really bad. Except for the first success installation, still don't know how it works, all subsequent installation failed here and there.

A new error about msrestazure hit me as below (never encountered before). Any idea what went wrong, and how to fix it?

-------------------------------------------------------------
Searching for msrestazure
Reading https://pypi.python.org/simple/msrestazure/
Best match: msrestazure 0.4.7
Downloading https://pypi.python.org/packages/04/67/8ab1713acc26d666008ec4fc62815adf6aef611a553e74d181f851a13cdf/msrestazure-0.4.7.zip#md5=4a3c9506ebcc9a78685d78c8beab90eb
Processing msrestazure-0.4.7.zip
Writing /tmp/easy_install-jSlpBK/msrestazure-0.4.7/setup.cfg
Running msrestazure-0.4.7/setup.py -q bdist_egg --dist-dir /tmp/easy_install-jSlpBK/msrestazure-0.4.7/egg-dist-tmp-93iEy8
error: Setup script exited with error in msrestazure setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
Unable to complete AppScale tools installation.
failed!
-------------------------------------------------------------

**Comment by cdonati** [comment]
There is no limitation on the S3 bucket. Until we get a more accessible mirror up, I would recommend manually copying in the needed files to /var/cache/appscale so that the build script does not need to download them.

The syntax in the msrestazure package's setup.py file is not compatible with the version of setuptools that is included in trusty. Typically, pip installs the package from the wheel, so I hadn't seen this issue with a newer `pip`. However, it looks like your machine is attempting to install the package from the source distribution. I opened up a pull request (https://github.com/AppScale/appscale-tools/pull/611) that should fix the issue. You can also run `pip install "setuptools>=8.0,<34"` and retry the appscale-tools build.

**Comment by obino** [comment]
We are working on providing ready images in China.
